/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
int add(int a,int b)
{
	int c=0;

	//__asm volatile("ADD %0,%1,%2":"=r"(c):"r"(a),"r"(b));
	__asm volatile("ADD %[res],%[a],%[b]":[res]"=r"(c):[a]"r"(a),[b]"r"(b));
}

int main(void)
{
	int a=10,b=20,c=0;
	c=add(a,b);


}
