/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include<stdio.h>
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
int add(int x1,int x2,int x3, int x4)//callie
{
	int sum=x1+x2+x3+x4;
	return sum;
}

int main(void)
{
	int s= add(1,2,3,4);//caller
	printf("sum of the values is %d \n",s);
	int b=10;
	printf(" the values is %d \n",b);

	/* Loop forever */
	//for(;;);
}


