/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include<stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void change_accesslevel_pri()
	{
		__asm volatile("MRS R0,CONTROL");
		__asm volatile("AND R0,R0,#0x00");
		__asm volatile("MSR CONTROL,R0");
	}

void generate_interrupt(){

	uint32_t *pSTIR = (uint32_t*)0xE000EF00;
	uint32_t *pISER0 = (uint32_t*)0xE000E100;
	//these are some ARM Cortex M4 procssor system control register which can only be access being in privilege access level
	//any attempt to try to change contents of these register in being in unprivilege mode will cause a processor fault EXCEPTION


	//GENERATE SOFTWARE INTERRUPT FOR IRQ3
	*pISER0 |= (1<<3);
	*pSTIR = (3 & 0x1FF);
}
void change_accesslevel_unpri()
	{
		__asm volatile("MRS R0,CONTROL");
		__asm volatile("ORR R0,R0,#0x01");
		__asm volatile("MSR CONTROL,R0");
	}

int main(void)
{
    /* Loop forever */
	//for(;;);
	printf("In thread mode : before interrupts \n");
	change_accesslevel_unpri();
	change_accesslevel_pri();
	generate_interrupt();
	printf("In thread mode : after interrupts \n");
}

void RTC_WKUP_IRQHandler(void)
{
	printf("In Handler mode  : ISR \n");
}

void HardFault(void)
{
printf("Hard Fault Detected \n");
while(1);
}
